### ISSUE TITLE
Posting of constraints is slow when propagation engine is set before

### ISSUE THREAD

**Issue by gregy4** [chocoteam/choco3#295]
In my code I use TwoBucketPropagationEngine, profiler showed me that a lot is spend in Solver.post method and that dynamic addition is used.

Workaround that speed my code was to set propagation engine after constraints are already posted. Best solution is probably to not use dynamic addition until start of searching.

To set propagation engine I use following command
     solver.set(new TwoBucketPropagationEngine(solver));

The problem happened in choco 3.3.0, quick look at current branch showed me there's no change in a code that fix it.

**Comment by cprudhom** [comment]
Yes, that's true.
Indeed, the propagation engine can be created whenever you want, but as soon as a call to `solver.propagate()` is made, the engine is in a state where new constraint additions have to be made with respect to previously added ones.
Sadly, the propagation engine is not a simple list of propagator to propagate, but internal data structures need to be created/updated in order to provide good performances when solving a problem.

There is no solution, but to delay as possible the creation of the propagation engine or erase it when multiple constraints are added between two propagations. 

I know it is the default prop engine in 3.3.0, but if there is another reason, could you tell me why  you choose `TwoBucketPropagationEngine()` ?

**Comment by gregy4** [comment]
Understand. Maybe solution can be to be able to set default propagation engine by class and let solver to create an instance when needed (before solver.propagate()) and not already assigned to a solver. Otherwise other users can again rediscover same performance problem ...

I use TwoBucketPropagationEngine because it is much faster in my case than SevenQueuesPropagatorEngine in 3.3.0.

**Comment by cprudhom** [comment]
That's what is done actually. 
Could you tell me more about your use case?

**Comment by gregy4** [comment]
Hi Charles, my use case is about scheduling of tasks that use not only resources (represented directly by cumulative constraints) but also human resources with skills. I sent you working example already when we were solving problem with Solver.duplicate method. The model was also consulted with Jean-Guillaume last year.

I checked current develop branch and found that SevenQueuesPropagatorEngine is faster compared to 3.3.0 but still slower compared to TwoBucketPropagationEngine. In 3.3.0 it took 22% more time to find first solution, in develop branch it is 17%.

**Comment by cprudhom** [comment]
OK, thank you for the evaluation.
My point was about the slowing down observed when the propagation was already initialized: do you propagate constraint as long as you posted it? Or do you solve partially the problem before adding new constraint? 
My questions are relative to the process you are using which results in adding "dynamically" constraints to the engine. (Sorry, I can't find your code on my computer anymore, so I can't figure out by myself).

**Comment by gregy4** [comment]
No, I don't propagate constraints. I post constraints using solver.post method and after all constraints and variables are in a model I call solver.findOptimalSolution method.

**Comment by cprudhom** [comment]
Ok, so I got it. You set the engine before adding the constraints, right?
I'll fix that, so that initializing the engine is not done on the constructor.

**Comment by gregy4** [comment]
Yes, you are right.
