### ISSUE TITLE
scalar, sum: refactoring

### ISSUE THREAD

**Issue by cprudhom** [chocoteam/choco3#324]
The way arithmetic constraints are currently managed is a little fuzzy.
There should one and unique entry method which enable reducing and selecting the correct propagator to post.
Further more, evaluations shown that maintaining only one implementation of PropScalarEq (the same goes with PropSumEq and PropBoolSum) is performance killer when different operators are required (such as <= or >=).
A good example is triangular (MZN2015).

**Comment by cprudhom** [comment]
There should be a normalize step (to remove redundant coefficients or useless variables) and a second step of selection : looking at arity, then type of variables (boolean or int) and then specific cases.

**Comment by cprudhom** [comment]
I suggest a common Constraint (named IntLinComb for instance, like in Choco2) to deal with that.

**Comment by cprudhom** [comment]
The new version seems to works as expected, on the majority of the problems (i.e., better or equivalent).
But, it is clear that there is still a need for:
- a sum (and scalar?) of boolean which comes with various operator (see 2012/carpet-cutting, 2012/league, 2012/vrp and IntLinLeBuilder)

**Comment by cprudhom** [comment]
There is still a question on when posting 
```java
solver.post(IntConstraintFactory.scalar(bs, as, "<=", c));
```
instead of :
```java
int[] tmp = IntLinCombFactory.getScalarBounds(bs, as);
IntVar scal = VF.bounded(StringUtils.randomName(), tmp[0], tmp[1], solver);
solver.post(ICF.scalar(bs, as, "=", scal));
solver.post(ICF.arithm(scal, "!=", c));
```
(the same goes with the <, >, >=, !=)

On MZN instances, it is not obvious which one to choose.

**Comment by mwahbi** [comment]
Hi lads, 
By the way, I think there is a small problem in Scalar that may change a lot. 
https://github.com/chocoteam/choco3/blob/develop/choco-solver/src/main/java/org/chocosolver/solver/constraints/nary/sum/Scalar.java#L109

I think instead of <code>0</code> we need <code>Integer.MAX_VALUE</code> to get: 
<code>int min = Math.min(Integer.MAX_VALUE, vars[i].getLB() * coefs[i]);</code>  

The same thing for https://github.com/chocoteam/choco3/blob/develop/choco-solver/src/main/java/org/chocosolver/solver/constraints/nary/sum/Scalar.java#L111

I think instead of <code>0</code> we need <code>Integer.MIN_VALUE</code> to get: 
<code>int max = Math.max(Integer.MIN_VALUE, vars[i].getLB() * coefs[i]);</code>  

Right?

**Comment by cprudhom** [comment]
I think this is done in order to avoid integer overflows/underflows.
Furthermore, this is not called anymore and I deprecated it in the current branch (and it will be deleted soon).
