### ISSUE TITLE
getPropagationConditions for array of variables of dynamic length

### ISSUE THREAD

**Issue by JLiangWaterloo** [chocoteam/choco3#328]
Consider a propagator that takes two arrays of IntVars. As of right now I'm having trouble specifying the propagation conditions for the two arrays. Consider the Java code below:

```java
public class VariableArgPropagator extends Propagator<IntVar> {

    private final IntVar[] v1s, v2s;

    public VariableArgPropagator(IntVar[] v1s, IntVar[] v2s) {
        super(ArrayUtils.append(v1s, v2s), PropagatorPriority.UNARY, true);
        this.v1s = v1s;
        this.v2s = v2s;
    }

    @Override
    public int getPropagationConditions(int vIdx) {
        if (vIdx < v1s.length) {
            return IntEventType.boundAndInst();
        }
        return IntEventType.instantiation();
    }

    @Override
    public void propagate(int evtmask) throws ContradictionException {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public ESat isEntailed() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public static void main(String[] args) {
        Solver s = new Solver();
        IntVar[] v1s = VF.enumeratedArray("v1", 3, 0, 3, s);
        IntVar[] v2s = VF.enumeratedArray("v2", 3, 0, 3, s);
        s.post(new Constraint("VariableArg", new VariableArgPropagator(v1s, v2s)));

        s.findSolution();
    }
}
```

The code will throw a null pointer exception. This is because the super constructor calls "getPropagationConditions" before the variables are initialized! And I can't initialize the variables before calling the super constructor...

Is there a way around this? Thanks.

**Comment by cprudhom** [comment]
You can have a look at [PropFullCumulative](https://github.com/chocoteam/choco3/blob/develop/choco-solver/src/main/java/org/chocosolver/solver/constraints/nary/cumulative/PropFullCumulative.java) where such a hack is made.
The problem comes from the  `linkVariables()`, called by the `Propagator` constructor, which calls `getPropagationConditions()`. So the patch consists in:
- declaring an empty `linkVariables()` in your propagator ([see](https://github.com/chocoteam/choco3/blob/develop/choco-solver/src/main/java/org/chocosolver/solver/constraints/nary/cumulative/PropFullCumulative.java#L118)),
- call `super.linkVariables()` in the constructor ([see](https://github.com/chocoteam/choco3/blob/develop/choco-solver/src/main/java/org/chocosolver/solver/constraints/nary/cumulative/PropFullCumulative.java#L96)).

We may need to revamp the way variables are linked to a propagator, may be during initial propagation...

Hope it helps,
CP

**Comment by JLiangWaterloo** [comment]
This works, although not pretty.
