### ISSUE TITLE
Choco 3.3.2: what happened to solver.searchLoop.interrupt

### ISSUE THREAD

**Issue by RobertHilbrich** [chocoteam/choco3#345]
We used `solver.searchLoop.interrupt` to interrupt the solver while it is still searching, for instance, when the user clicked "Abort" in the UI. Unfortunately, it has been deprecated by just throwing an `UnsupportedOperationException`. What is the recommended way to interrupt the search manually?

**Comment by cprudhom** [comment]
Now, there is only one way to stop the search, it is through a `org.chocosolver.util.criteria.Criterion` which is an interface to be extended, equipped with a single method `boolean isMet()`.

When the stop criterion is met, the method should return `true` (`false` otherwise) and the search loop, which regularly checks criteria, stops when at least one the declared one returns `true` (a disjunction).

Any criterion should be added to the `Solver` thanks to `s.addStopCriterion(Criterion)`.
For example, when dealing with [parallel resolution](https://github.com/chocoteam/choco3/blob/master/choco-solver/src/main/java/org/chocosolver/solver/search/loop/monitors/SearchMonitorFactory.java#L380), the following stop criteria are added to solver:
```java
AtomicInteger finishers = new AtomicInteger(0);
solvers.stream().forEach(s -> s.addStopCriterion(()->finishers.get()>0));
solvers.stream().forEach(s -> s.plugMonitor(new IMonitorClose() {
    @Override
    public void afterClose() {
        int count = finishers.addAndGet(1);
        if(count == solvers.size()){
            finishers.set(0); //reset the counter to 0
        }
    }
}));
```

Anytime a solver ends, it increments counter by 1.
Anytime a running solver checks the counter and that its value is strictly greater than 0 (i.e., at least one solver already ends), its search ends (and the counter is incremented by 1 too).
The last ending solver reset the counter to 0.

**Comment by gregy4** [comment]
Well, it doesn't comply with the word deprecated ...
Best way to remove the method interrupt is to deprecate it in one version - internally implement it through addStopCritecion method and describe recommended alternative. Please update minimally javadoc of interrupt method.
I used interrupt method with only String argument that is completely missing, without this issue I would probably try to match with deprecated but compilable version and finally found that I wasted my time because deprecated method isn't also functional.

**Comment by cprudhom** [comment]
Sorry for the time loss, I'll pay attention to that in the future when I "deprecate" methods or class, to indicate what replaces (if any) the deprecated method or class. 
I'll try to follow [this advices](https://javax0.wordpress.com/2014/02/05/use-java-annotation-deprecated-the-right-way/).

Note that, a method or class annotated as deprecated will presumably be absent in the following release.

**Comment by RobertHilbrich** [comment]
Thanks - it works fine!
