### ISSUE TITLE
Choco 3.3.2: IntEventType Remove is no longer part of IncLow or DecUpp

### ISSUE THREAD

**Issue by RobertHilbrich** [chocoteam/choco3#347]
We wrote some customized versions of an `inverse_channel` propagator based on `PropInverseChannelAC`. Within this code, we tried to distinguish between instantiation-events and value-removal events. In previous choco-versions we just called `IntEventType.isRemove(mask)` to check, if there has been a value removal event.

With choco 3.3.2, `IntEventType.isRemove(mask)` returns `false` even if there has been a `DECUPP`or `INCLOW` event. I think this may be confusing to people, as a change in the lower or upper bound is a result of a value removal - or not?

**Comment by cprudhom** [comment]
I changed `IntEventType` in 3.3.2, as you noticed, in order to simplify some stuff.
But I believe some explanations are required, sorry in advance that was already known.

Event types (integer here) are used with four different purposes.

But first of all, there is a hierarchy between events, as you said, `REMOVE` is the *smallest* one, `INCLOW` and `DECUPP` are equivalent and induce `REMOVE` and `INSTANTIATE` is the *greatest* and induced the three lower ones. In other words, increasing the lower bound of a variable is equivalent to removing all values from old LB to new LB-1.   

Now, the purposes:

1. in `Propagator.getPropagationConditions(int i)`. It helps sorting the propagator of the variable `i` with respect to the types of event they can deal with. Propagators which react to the same type of events are placed in the same "bucket". Thus, when the variable `i` is modified, only propagators which are able to deduce something from that event are called. In that case, combinations of events are allowed, such as `{REM, INCLOW}` or `{REMOVE, INCLOW, DECUPP, INSTANTIATE}`, and are stored, for each variable, with the help of bit mask. 

2. when the variable is actually modified. Any propagators can modify its variable, always through one of the provided methods, such as `v.instantiateTo(int, ICause)` or `v.updateLowerBound(int, ICause)`.
In that case, when the propagation engine is triggered, with only single one event as input: `INSTANTIATE` or `INCLOW`. Then, in the propagation engine, the event is stored, possibly merged with not propagates ones, for future execution.

3. when a propagator is selected for propagation, the events its variables have registered are treated sequentially. Here, if a variable has registered multiple events, the union is given as input to the propagator through `p.propagate(int, int)`. In this method, it may happen that the events registered are filtered, calling `IntEventType.isRemove(int)` or `IntEventType.isBound(int)`, to adapt the filtering to the type of events registered. Note that the conditional tests should consider that events can be merged.

4. for explanations, but I won't go into details here.

Since there is no bug in [SevenQueuesPropagatorEngine, l.255](https://github.com/chocoteam/choco3/blob/master/choco-solver/src/main/java/org/chocosolver/solver/propagation/hardcoded/SevenQueuesPropagatorEngine.java#L255) (the code is: `eventmasks[aid][pindice] |= type.getMask();` does what I expect), I believe that the unexpected behavior comes from step 3. and `IntEventType.isRemove(int)` and others.
In version 3.3.1, the hierarchy of events was stated *inside* the event. So when your propagator received an `INCLOW` event, testing wether it is also `REMOVE` returned `true` which is not the case in 3.3.2, right? 

To be honest, I missed your case, since only one constraint calls `IntEventType.isRemove(int)` ([PropDistanceXYC](https://github.com/chocoteam/choco3/blob/master/choco-solver/src/main/java/org/chocosolver/solver/constraints/binary/PropDistanceXYC.java#L132)) and the conditions are not exclusive.

I have to think about how you request can (or cannot) be integrated smartly.
A patch is to avoid exclusive conditions on event mask.

**Comment by cprudhom** [comment]
Maybe I can make clearer the fact that I only call `IntEventType.isRemove(int)` only once in the source code, while many propagators react on removals.

If a propagator reacts on value removals, it is executed on any events occurring on the variable(s), since `REMOVE` is the *smallest* event. Then, if other type of event occurs, it is *greater* and maybe a specific and/or more efficient algorithm can be used **instead**.
So, we prefer testing whether an event is greater than smaller. 
More over, using deltas, we can iterate over newly removed values, without paying interest to the type of events registered.

**Comment by RobertHilbrich** [comment]
Thank you for your explanations and taking the time to explain the inner mechanics. 

Just a simple suggestion: wouldn't it be sufficient to change lines 97-99 in IntEventType.java from 
```java
public static boolean isRemove(int mask) {
        return (mask & REMOVE.mask) != 0;
    }
```
to
```java
public static boolean isRemove(int mask) {
        return mask > 0;
    }
```
since the removal event is the smallest event and thus part of any other event - except `VOID`?

**Comment by cprudhom** [comment]
Well, the correct method should be:
```java
public static boolean isRemove(int mask) {
        return true;
    }
```
since `VOID` are filtered by the propagation engine and never passer as argument to a propagator, plus any events different from `REMOVE` are *greater* than `REMOVE`. 

I really think calling `isRemove(int)` should be the very last choice, when any other alternatives have been evaluated.

**Comment by RobertHilbrich** [comment]
Okay - you are right ... but we are using enumerated variables and we are interested in the `REMOVE` event, because we want to get notified even if values are removed "in the middle" of the domain, so neither the upper nor the lower bound changes (and no instantiation is happening as well).

**Comment by cprudhom** [comment]
Do you mean you develop a propagator which "completes" another one, and which should only be informed of values removed in the middle of the domain, and not any other type of events?

It true, you can bypass your call to `isRemove(int)` by `mask > 0`, even if, I agree, it is a little bit ugly.

Maybe I can add a new method, like `isAtLeastRemove(int)` (certainly with a better name).

**Comment by cprudhom** [comment]
I read your last answer twice, and here is a more appropriate answer.

When, in your propagator, you declare `getPropagationConditions(int i)` like this:
```java
@Override
public int getPropagationConditions(int vIdx) {
    return IntEventType.boundAndInst();
}
```
your propagator will be informed anytime one if its variables is modified by any events **but** `REMOVE` (that is `INCLOW` and/or `DECUPP` and/or `INSTANTIATE`).

On the contrary, if you defined something like:
```java
@Override
public int getPropagationConditions(int vIdx) {
    return IntEventType.all();
}
```
your propagator will be informed anytime one of its variable is modified by any events.

Later, when your propagator is actually executed, the aggregated events mask is given as input (2nd parameter of `propagate(int i,int m)`), and here you can adapt the algorithm to the events got.

Indeed, you can have  a merge event made of `DECUPP` and `INCLOW` and `REMOVE` which indicates that:
- the upper bound of  the variable `i` has decreased,
- its upper bound has increased and
- some values has been removed between old LB and old UB (see the following note).

Note that, if a variable`v={1,2,3,4,5,6}` is chronologically modified like this:
1. `v \ {2}`
2. `v < 6`
3. `v > 3`
then the first event ( `v \ {2}`) is subsumed by the third one (`v > 3`). 
There is no efficient way to consider the subsumption by the propagation engine.

**Comment by RobertHilbrich** [comment]
Well, I am learning a lot from you about choco. Our customized version of the `PropInverseChannelAC.java` propagator never overrides `getPropagationConditions`. Therefore it uses the default implemention and registers for `ALL_EVENTS`.

Within the `propagate` methods of the `PropInverseChannelAC.java` we want to distinguish two events for enumerated variables: instantiation events and value removal events. We do not care too much about about changes in upper or lower bounds as we want to enforce some kind of AC.

In Choco 3.3.1 we just needed to have an if-clause on the mask and check whether it was a removal event or instantiation event. This stopped working, so as a workaround, we check for isRemove, DECUPP or INCLOW.

So - no worries! But thank you for your explanations!
