### ISSUE TITLE
Overflow exception for modest-sized multiplications

### ISSUE THREAD

**Issue by JLiangWaterloo** [chocoteam/choco3#353]
For example, the following code will throw an exception.

```java
public static void main(String[] args) {
    Solver s = new Solver();
    IntVar i1 = VF.enumerated("i1", 0, 46500, s);
    IntVar i2 = VF.enumerated("i2", 0, 46500, s);
    s.post(ICF.times(i1, 46500, i2));
}
```

The exception is:

```
Exception in thread "main" org.chocosolver.solver.exception.SolverException: Integer overflow.
Consider reducing the variable domains.
	at org.chocosolver.solver.constraints.binary.PropScale.<init>(PropScale.java:74)
	at org.chocosolver.solver.constraints.IntConstraintFactory.times(IntConstraintFactory.java:457)
```

Should the allowed domains for multiplication be expanded? The program above used only medium-sized numbers and it still caused overflow.

**Comment by gregy4** [comment]
For calculated or aggregated variables it makes sense to me also. Question is performance penalty when for example BigInteger will be used.

**Comment by JLiangWaterloo** [comment]
It's probably sufficient to do any multiplication calculation with 64-bit longs.

**Comment by cprudhom** [comment]
The constraint input checker is not correct, I'll suggest a patch asap.

**Comment by cprudhom** [comment]
Indeed, the test is too strict, and needs to be removed, since Y is an integer constant and no overflow can be created with such configurations. As example, I added the following (success) test:
```java
Solver s = new Solver();                                                                  
IntVar i1 = VF.bounded("i1", Integer.MIN_VALUE /10, Integer.MAX_VALUE /10, s);            
IntVar i2 = VF.bounded("i2", Integer.MIN_VALUE/10, Integer.MAX_VALUE/10, s);              
s.post(ICF.times(i1, 10000, i2));                                                         
s.findAllSolutions();                                                                     
Assert.assertEquals(s.getMeasures().getSolutionCount(), Integer.MAX_VALUE/100000 * 2 + 1);
```

**Comment by gregy4** [comment]
What is your opinion on BigInteger support ?
Problem with integer overflow is more general, in scalar constraint for example overflow isn't identified (I checked it last time in 3.3.1 version I think) and it is quite hard to find out what is wrong.

I understand that can take some time to implement it, at first it could be fine to be able to define a variable with BigInteger domain and a constraint using the variable.

For integer variables I just need to be aware of potential integer overflow.

**Comment by cprudhom** [comment]
Honestly, I never considered such question. 
First of all, I'm not aware of more that a dozen of propagators candidate to integer under/overflow (arithmetic ones mainly), so I am prone to deal with them one by one.
Then, for performance issues, in Choco, we try to use as many primitives as possible, avoiding objects such as `Integer` or `Long` (for auto-boxing purposes). That's why Choco relies on [trove4j](http://trove4j.sourceforge.net), or specific implementation, when lists of ints are needed.
Moreover, Constraint Programing deals with backtracking. In Choco, this is related to `Environment`: either trailing (default one) or copying.This ensures that primitives are backtrackable (eg., `IStateInt`, and `StoredInt` or 'RcInt`). All variables and almost all propagators rely on one or more backtrackable primitive (or equivalent). For example, a bounded integer variable relies on three (backtrackable) `int`s (lower bond, upper bound and size). The environment is critical since anytime a domain is read or written, a specific operation needs to be run. 
Finally, I have a negative *a priori* about using `BigInteger` because of the javadoc indicates that:
```html
 * BigInteger constructors and operations throw {@code ArithmeticException} when
 * the result is out of the supported range of
 * -2<sup>{@code Integer.MAX_VALUE}</sup> (exclusive) to
 * +2<sup>{@code Integer.MAX_VALUE}</sup> (exclusive).
```
Saying that, since `ISateInt` and `IntVar` are interfaces, nothing prevents from creating such backtrackable `BigInteger` and under/overflow-safe IntVar, at least for debugging purpose.

**Comment by gregy4** [comment]
Thanks for your description of choco internals, I'll look at IStateInt and IntVar interfaces.
I quickly checked at BigInteger limits and it seems to me that the limits are caused by maximal size of int array in java (present in each BigInteger instance) so no real problem - slow performance and high memory usage of BigInteger instances close to java limits should safely prevent everybody to work with such big numbers.
